---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170602144934"
generator:
  name: "UniversalSeed"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.1.75"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers"
    branch: "xml-type"
    sha: "d24dfb7"
  parameters:
    - "org": "jessitron"
    - "repo": "elm-rugs"
    - "branch": "master"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.1-LANGEXT"
editor:
  name: "AddTypeScriptEditor"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.31.0-20170601202105"
  origin:
    repo: "https://github.com/atomist/rug-rugs.git"
    branch: "d1145f3450f22af598a278ccc475eb18f3c0f5e4"
    sha: "d1145f3"
  parameters:
    - "editorName": "AddToModel"
    - "description": "add a field to the model"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.1-LANGEXT"
editor:
  name: "BumpVersion"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.31.0-20170601202105"
  origin:
    repo: "https://github.com/atomist/rug-rugs.git"
    branch: "d1145f3450f22af598a278ccc475eb18f3c0f5e4"
    sha: "d1145f3"
  parameters:
    - "component": "minor"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.1-JESS"
editor:
  name: "BumpVersion"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.31.0-20170601202105"
  origin:
    repo: "https://github.com/atomist/rug-rugs.git"
    branch: "d1145f3450f22af598a278ccc475eb18f3c0f5e4"
    sha: "d1145f3"
  parameters:
    - "component": "minor"

